### ISSUE TITLE
Karmada 致命缺点的疑问？

### ISSUE THREAD

**Issue by jxiewei** [henrywangx/henrywangx.github.io#7]
但是Karmada也有致命的缺点：对象会在global集群被处理。例如用户创建一个Deployment，实际上global集群里面也会创建这个deployment。
-- 这里是否有误？global 集群的controller-manager阉割过了，不会reconcile deployment了吧？

**Comment by henrywangx** [comment]
> 

@jxiewei sorry，之前这里理解错了，一直没来得及修改，我会尽快修改，简书上已经修改过了。当然这样的话，我理解karmada不能和global k8s集群放在一起了，而是直接替换了global k8s集群
